In [93]:
import pandas as pd
import os

dfs = {}
for file in os.listdir("./Raw"):
    if file.endswith(".csv"):
        dfs[file.split(".csv")[0]] = pd.read_csv(f"./Raw/{file}")

In [106]:
dfs_sheets = {}
for key in dfs:
    if "Sheets" in key:
        dfs_sheets[key] = dfs[key]

dfs_partiful =  {}
for key in dfs:
    if "Partiful" in key:
        dfs_partiful[key] = dfs[key]

dfs_posh = {}
for key in dfs:
    if "Posh" in key:
        dfs_posh[key] = dfs[key]

dfs_others = {}
for key in dfs:
    if key not in dfs_sheets and key not in dfs_partiful and key not in dfs_posh:
        dfs_others[key] = dfs[key]

# print lengths of each dictionary
print("Length of dfs: ", len(dfs))
print("Length of dfs_sheets: ", len(dfs_sheets))
print("Length of dfs_partiful: ", len(dfs_partiful))
print("Length of dfs_posh: ", len(dfs_posh))
print("Length of dfs_others: ", len(dfs_others))

# track totals observations
total_len = 0
for df in dfs.values():
    total_len += len(df)

Length of dfs:  23
Length of dfs_sheets:  11
Length of dfs_partiful:  6
Length of dfs_posh:  4
Length of dfs_others:  2

# Merging

In [107]:
df_all_people = pd.DataFrame(columns=["First Name", "Last Name", "Email", "School", "Grade","Gender", "Is_Jewish"])

In [108]:
# show head of each df in sheets
for key in dfs_sheets:
    print(f"Head of {key}")
    display(dfs_sheets[key].head())

Head of Viale_Sheets

             name   school      grade gender j/n email
0  Zakarias Erdos  Harvard     Junior      M   J  <NA>
1     Zach Abrams  Harvard     Junior      M   J  <NA>
2    Jen Ben Arye      MIT  Sophomore      F   J  <NA>
3   Logan Goodman      MIT   Freshman      F   J  <NA>
4      Kim Nahari  Harvard     Junior      F   J  <NA>

Head of CommunityDinners_Sheets

                    name   school     grade gender j/n email
0          Jane Lichtman  Harvard    Junior      F   J  <NA>
1          Alana Fuentes  Harvard  Freshman      F   N  <NA>
2  Isabella Raskin Calvo  Harvard  Freshman      F   J  <NA>
3            Almog Hilel      MIT    Senior      M   J  <NA>
4          Robbie Khazan      MIT    Junior      M   J  <NA>

Head of PreLaunch_Sheets

,name,email,school,grade,gender,j/n
0,Ted Sunshine,theodore_sunshine@college.harvard.edu,Harvard,Junior,M,J
1,Zach Abrams,zachabrams@college.harvard.edu,Harvard,Junior,M,J
2,Danny Denenberg,dannydenenberg@gmail.com,Harvard,Junior,M,J
3,Zakarias Erdos,zakarias_erdos@college.harvard.edu,Harvard,Junior,M,J
4,Doron Ben Haim,doronbenhaim@college.harvard.edu,Harvard,Sophomore,M,J

Head of ZelnickSpeaker_Sheets

                 name   school  grade  gender  j/n email
0         Yehudah Tor  Harvard    NaN     NaN  NaN  <NA>
1       Charlie Covit  Harvard    NaN     NaN  NaN  <NA>
2      Zakarias Erdos  Harvard    NaN     NaN  NaN  <NA>
3  Benjamin Kushmakov  Harvard    NaN     NaN  NaN  <NA>
4            Skye Lam    Other    NaN     NaN  NaN  <NA>

Head of SababaNights_Sheets

                name school      grade gender  j/n email
0              Clyde    MIT     Senior    NaN  NaN  <NA>
1              Miles    MIT     Senior    NaN  NaN  <NA>
2       Anna Erskine    MIT  Sophomore    NaN  NaN  <NA>
3          Kevin Zhu    MIT  Sophomore    NaN  NaN  <NA>
4  Mercedes randhahn    MIT  Sophomore    NaN  NaN  <NA>

Head of SecretSip_Sheets

              name   school     grade gender j/n email
0       Alex Stone  Harvard    Junior      M   J  <NA>
1      Almog Hilel      MIT    Senior      M   J  <NA>
2    Arav Bhargava  Harvard  Freshman      M   N  <NA>
3  arielle frommer  Harvard    Senior      F   J  <NA>
4   Atara Rubinson  Harvard  Freshman      F   J  <NA>

Head of Amplify_Sheets

             name   school      grade gender j/n email
0      Ana Tejada      MIT  Sophomore      F   N  <NA>
1  Atara Rubinson  Harvard   Freshman      F   J  <NA>
2  Becca Ackerman  Harvard     Senior      F   J  <NA>
3     Bobby Cupps  Harvard     Junior      M   N  <NA>
4    Carly Bolton  Harvard     Junior      F   N  <NA>

Head of ZelnickDinner_Sheets

            name   school  grade  gender  j/n email
0  Brook Pulling      MIT    NaN     NaN  NaN  <NA>
1       Linda He  Harvard    NaN     NaN  NaN  <NA>
2             AJ    Other    NaN     NaN  NaN  <NA>
3            Ted    Other    NaN     NaN  NaN  <NA>
4          Chris    Other    NaN     NaN  NaN  <NA>

Head of Russell_Sheets

,name,email,school,grade,gender,j/n
0,Hiro Kondo,hirokondo@college.harvard.edu,Harvard,Junior,M,N
1,Zakarias Erdos,zakarias_erdos@college.harvard.edu,Harvard,Junior,M,J
2,Charlie Covit,charliecovit@college.harvard.edu,Harvard,Sophomore,M,J
3,Kidus Yohannes,kidusy@mit.edu,MIT,Senior,M,N
4,Ron Zalkind,NaN,Other,NaN,NaN,NaN

Head of Pentera_Sheets

                name   school  grade  gender  j/n email
0     Zakarias Erdos  Harvard    NaN     NaN  NaN  <NA>
1         Yael Danon  Harvard    NaN     NaN  NaN  <NA>
2  Alex Gerstenhaber  Harvard    NaN     NaN  NaN  <NA>
3        Yehudah Tor  Harvard    NaN     NaN  NaN  <NA>
4        Zach Abrams  Harvard    NaN     NaN  NaN  <NA>

Head of Launch_Sheets

,name,email,school,grade,gender,j/n
0,Adrian Maydanich,adrian.maydanich@gmail.com,Harvard,Freshman,M,J
1,Airi Furui,airi6269@gmail.com,Harvard,Junior,F,N
2,Alessandro Drake,adrake@college.harvard.edu,Harvard,Junior,M,N
3,Alex Gerstenhaber,Alexgerstenhaber@college.harvard.edu,Harvard,Junior,M,J
4,Alexa Cohen,acohen27@mit.edu,MIT,Sophomore,F,J

In [109]:
# Process sheets
target_cols = ["name","email","school","grade","gender","j/n"]
for key in dfs_sheets:
    df = dfs_sheets[key]
    for col in target_cols:
        if col not in df.columns:
            df[col] = pd.NA
    df = df[target_cols]
    df.columns = ["Name", "Email", "School","Grade", "Gender", "Is_Jewish"]
    # robust to only first names
    df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
    df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
    df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
    df["First Name"] = df["First Name"].astype(str).str.lower()
    df["Last Name"] = df["Last Name"].astype(str).str.lower()

    # make school lower case
    df["School"] = df["School"].astype(str).str.lower()
    df["School"] = df["School"].astype(str).str.lower()

    # make grade into class year freshman = 2028, sophomore = 2027, junior = 2026, senior = 2025
    df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)

    # gender
    df["Gender"] = df["Gender"].astype(str).str.upper()

    # is_jewish
    df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)

    df_all_people = pd.concat([df_all_people, df])

/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/463772809.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [110]:
for key, df in dfs_partiful.items():
    display(df)

,name,registered,approved,rsvp_date,email,school,grade,gender,j/n
0,Aaron Bradford,1,0,2024-11-08 00:38:57,<NA>,<NA>,<NA>,<NA>,<NA>
1,Abby miller,1,1,2024-11-04 19:16:33,<NA>,<NA>,<NA>,<NA>,<NA>
2,Abby Rabinowitz,1,1,2024-11-03 16:49:54,<NA>,<NA>,<NA>,<NA>,<NA>
3,Abe Kohl,1,1,2024-11-07 22:40:40,<NA>,<NA>,<NA>,<NA>,<NA>
4,Abhay Duggirala,1,0,2024-11-08 03:15:05,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
446,Zev Moore,1,1,2024-11-07 06:41:40,<NA>,<NA>,<NA>,<NA>,<NA>
447,Zijian Ma,1,1,2024-11-05 11:24:43,<NA>,<NA>,<NA>,<NA>,<NA>
448,Zoe Pasetsky,1,1,2024-11-07 22:40:12,<NA>,<NA>,<NA>,<NA>,<NA>
449,Zoe Zalkind,1,1,2024-11-06 02:16:51,<NA>,<NA>,<NA>,<NA>,<NA>
450,Zoë price,1,1,2024-11-05 22:15:08,<NA>,<NA>,<NA>,<NA>,<NA>

,name,registered,approved,rsvp_date,email,school,grade,gender,j/n
0,Aashrith Chejerla,1,0,2024-09-23 18:05:40,<NA>,<NA>,<NA>,<NA>,<NA>
1,Abby Rabinowitz,1,1,2024-09-22 21:55:50,<NA>,<NA>,<NA>,<NA>,<NA>
2,Abigail Kaplan,1,1,2024-09-23 14:46:31,<NA>,<NA>,<NA>,<NA>,<NA>
3,Abraham Krebs,1,1,2024-09-23 14:46:34,<NA>,<NA>,<NA>,<NA>,<NA>
4,Adam Cohen,1,0,2024-09-22 19:49:53,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
255,Zach Marinov,1,1,2024-09-26 17:41:07,<NA>,<NA>,<NA>,<NA>,<NA>
256,Zachary Starr,1,1,2024-09-23 04:25:31,<NA>,<NA>,<NA>,<NA>,<NA>
257,Ze Cavaco,1,0,2024-09-26 20:35:51,<NA>,<NA>,<NA>,<NA>,<NA>
258,Zeb Erdos,1,1,2024-09-21 15:07:14,<NA>,<NA>,<NA>,<NA>,<NA>
259,Zev Moore,1,1,2024-09-22 04:32:27,<NA>,<NA>,<NA>,<NA>,<NA>

,name,registered,approved,rsvp_date,email,school,grade,gender,j/n
0,Alex Gerstenhaber,1,1,2024-09-17 18:43:43,<NA>,<NA>,<NA>,<NA>,<NA>
1,Alexander Stone,1,1,2024-09-18 16:00:09,<NA>,<NA>,<NA>,<NA>,<NA>
2,Atara Rubinson,1,1,2024-09-18 16:00:04,<NA>,<NA>,<NA>,<NA>,<NA>
3,Benjy Firester,1,1,2024-09-18 19:21:12,<NA>,<NA>,<NA>,<NA>,<NA>
4,Carolina Bartunek,1,1,2024-09-19 22:48:49,<NA>,<NA>,<NA>,<NA>,<NA>
5,Cathy Campbell,1,1,2024-09-17 18:44:39,<NA>,<NA>,<NA>,<NA>,<NA>
6,Charlie Covit,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
7,Christopher Shen,1,1,2024-09-19 03:10:35,<NA>,<NA>,<NA>,<NA>,<NA>
8,Cora Barrett,1,1,2024-09-19 17:28:25,<NA>,<NA>,<NA>,<NA>,<NA>
9,Dana Rubin,1,1,2024-09-18 19:07:44,<NA>,<NA>,<NA>,<NA>,<NA>
10,Danny Denenberg,1,1,2024-09-16 14:54:25,<NA>,<NA>,<NA>,<NA>,<NA>
11,David Sunshine,1,1,2024-09-16 14:26:15,<NA>,<NA>,<NA>,<NA>,<NA>
12,Doron Ben Haim,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
13,Eduardo Vasconcelos,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
14,Eduardo Vasconcelos Goyanna Filho,1,1,2024-09-16 21:26:52,<NA>,<NA>,<NA>,<NA>,<NA>
15,Eliza Goler,1,0,2024-09-18 15:03:36,<NA>,<NA>,<NA>,<NA>,<NA>
16,ellyssa jeong,1,1,2024-09-18 15:54:46,<NA>,<NA>,<NA>,<NA>,<NA>
17,Emil Droga,1,1,2024-09-17 18:44:42,<NA>,<NA>,<NA>,<NA>,<NA>
18,Eric Kalimi,1,1,2024-09-17 17:23:30,<NA>,<NA>,<NA>,<NA>,<NA>
19,Ethan Rabinowitz,1,1,2024-09-19 17:28:22,<NA>,<NA>,<NA>,<NA>,<NA>
20,Giovanni M D’Antonio,1,1,2024-09-18 19:55:24,<NA>,<NA>,<NA>,<NA>,<NA>
21,Hannah,1,1,2024-09-16 20:12:41,<NA>,<NA>,<NA>,<NA>,<NA>
22,Hiro Kondo,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
23,Ittai kohavi,1,1,2024-09-19 22:48:25,<NA>,<NA>,<NA>,<NA>,<NA>
24,Jai glazer,1,1,2024-09-17 22:12:36,<NA>,<NA>,<NA>,<NA>,<NA>
25,Jane Lichtman,1,1,2024-09-16 20:12:40,<NA>,<NA>,<NA>,<NA>,<NA>
26,Jax Adler,1,1,2024-09-17 22:12:34,<NA>,<NA>,<NA>,<NA>,<NA>
27,Jonah Gurion,1,1,2024-09-18 19:21:22,<NA>,<NA>,<NA>,<NA>,<NA>
28,Julia Cherchever,1,1,2024-09-18 19:20:39,<NA>,<NA>,<NA>,<NA>,<NA>
29,Julia Freitag,1,1,2024-09-18 15:54:53,<NA>,<NA>,<NA>,<NA>,<NA>
30,Julia Montgomery,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
31,Jōsh Mysoré,1,1,2024-09-19 17:29:13,<NA>,<NA>,<NA>,<NA>,<NA>
32,Kim Nahari,1,1,2024-09-16 14:26:13,<NA>,<NA>,<NA>,<NA>,<NA>
33,Lal Kablan,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
34,Lauren Teichholtz,1,1,2024-09-18 15:54:51,<NA>,<NA>,<NA>,<NA>,<NA>
35,Logan Goodman,1,1,2024-09-18 19:20:47,<NA>,<NA>,<NA>,<NA>,<NA>
36,maia posternack,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
37,max palys,1,1,2024-09-19 19:38:22,<NA>,<NA>,<NA>,<NA>,<NA>
38,Michael Oved,1,1,2024-09-17 01:01:35,<NA>,<NA>,<NA>,<NA>,<NA>
39,Nathan Gershengorn,1,1,2024-09-18 15:54:40,<NA>,<NA>,<NA>,<NA>,<NA>
40,Nim Ravid,1,1,2024-09-19 19:38:15,<NA>,<NA>,<NA>,<NA>,<NA>
41,Noa Goldstein,1,1,2024-09-19 14:59:22,<NA>,<NA>,<NA>,<NA>,<NA>
42,Noa Horowitz,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
43,Noa Renee Horowitz,1,1,2024-09-16 14:26:22,<NA>,<NA>,<NA>,<NA>,<NA>
44,Rachael Zacks,1,1,2024-09-18 19:21:29,<NA>,<NA>,<NA>,<NA>,<NA>
45,Rebecca Hirschfeld,1,1,2024-09-17 17:23:28,<NA>,<NA>,<NA>,<NA>,<NA>
46,Robert Fogel,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
47,Romi Wagner,1,1,2024-09-18 19:07:53,<NA>,<NA>,<NA>,<NA>,<NA>
48,Sadie Kargman,1,1,2024-09-16 14:51:30,<NA>,<NA>,<NA>,<NA>,<NA>
49,Salvatore Valentino,1,1,2024-09-18 21:03:02,<NA>,<NA>,<NA>,<NA>,<NA>
50,Segev Rome,1,1,2024-09-19 19:38:20,<NA>,<NA>,<NA>,<NA>,<NA>
51,Shir Somech,1,1,2024-09-17 23:15:01,<NA>,<NA>,<NA>,<NA>,<NA>
52,sydney bloch,1,1,2024-09-16 21:35:17,<NA>,<NA>,<NA>,<NA>,<NA>
53,Ted Sunshine,1,1,2024-09-19 15:49:02,<NA>,<NA>,<NA>,<NA>,<NA>
54,Uri Rolls,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
55,Will Sussman,1,1,2024-09-18 19:21:16,<NA>,<NA>,<NA>,<NA>,<NA>
56,Yael Danon,1,1,2024-09-19 19:38:18,<NA>,<NA>,<NA>,<NA>,<NA>
57,zach abrams,1,1,2024-09-16 14:10:50,<NA>,<NA>,<NA>,<NA>,<NA>
58,Zakarias Erdos,1,1,2024-09-16 13:11:53,<NA>,<NA>,<NA>,<NA>,<NA>
59,Zev Moore,1,1,2024-09-18 19:07:57,<NA>,<NA>,<NA>,<NA>,<NA>

,name,registered,approved,rsvp_date,email,school,grade,gender,j/n
0,Abhaya Ravikumar,1,1,2024-10-28 14:51:19,<NA>,<NA>,<NA>,<NA>,<NA>
1,Adam Ivatorov,1,1,2024-10-28 14:48:09,<NA>,<NA>,<NA>,<NA>,<NA>
2,Adam Zhou,1,1,2024-10-30 00:34:02,<NA>,<NA>,<NA>,<NA>,<NA>
3,AJ Sachwitz,1,1,2024-10-28 14:45:00,<NA>,<NA>,<NA>,<NA>,<NA>
4,Alana Fuentes,1,1,2024-10-29 17:46:27,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
111,Wilson Cheung,1,1,2024-10-29 17:46:51,<NA>,<NA>,<NA>,<NA>,<NA>
112,Yael Danon,1,1,2024-10-29 17:45:09,<NA>,<NA>,<NA>,<NA>,<NA>
113,yagmur kavukcuoglu,1,1,2024-10-29 17:45:34,<NA>,<NA>,<NA>,<NA>,<NA>
114,Yehudah Tor,1,1,2024-10-29 17:46:21,<NA>,<NA>,<NA>,<NA>,<NA>
115,Zach Abrams,1,1,2024-10-29 17:47:07,<NA>,<NA>,<NA>,<NA>,<NA>

,name,registered,approved,rsvp_date,email,school,grade,gender,j/n
0,Adrian Maydanich,1,1,2024-10-13 20:06:56,<NA>,<NA>,<NA>,<NA>,<NA>
1,Airi Furui,1,1,2024-10-13 20:07:02,<NA>,<NA>,<NA>,<NA>,<NA>
2,Alana Fuentes,1,1,2024-10-13 20:07:14,<NA>,<NA>,<NA>,<NA>,<NA>
3,Alexander Stone,1,1,2024-10-13 20:07:18,<NA>,<NA>,<NA>,<NA>,<NA>
4,Alexandra Friedlander,1,1,2024-10-13 20:07:20,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
95,Yael Danon,1,1,2024-10-13 20:13:59,<NA>,<NA>,<NA>,<NA>,<NA>
96,Yehudah Tor,1,1,2024-10-13 20:14:04,<NA>,<NA>,<NA>,<NA>,<NA>
97,Zach abrams,1,1,2024-10-13 20:14:08,<NA>,<NA>,<NA>,<NA>,<NA>
98,Zebulon Erdos,1,0,2024-10-14 23:12:14,<NA>,<NA>,<NA>,<NA>,<NA>
99,Zev Moore,1,0,2024-10-14 14:56:58,<NA>,<NA>,<NA>,<NA>,<NA>

,name,registered,approved,rsvp_date,email,school,grade,gender,j/n
0,Aaron Becker,1,1,2024-12-05 23:52:09,<NA>,<NA>,<NA>,<NA>,<NA>
1,Adrian Maydanich,1,1,2024-12-05 15:45:40,<NA>,<NA>,<NA>,<NA>,<NA>
2,Advay Goel,1,1,2024-12-05 16:22:53,<NA>,<NA>,<NA>,<NA>,<NA>
3,Alana Fuentes,1,1,2024-12-05 15:46:52,<NA>,<NA>,<NA>,<NA>,<NA>
4,Alex Gerstenhaber,1,1,2024-12-06 06:00:13,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
82,Wilson Cheung,1,1,2024-12-05 15:45:54,<NA>,<NA>,<NA>,<NA>,<NA>
83,Yehudah Tor,1,1,2024-12-05 15:46:09,<NA>,<NA>,<NA>,<NA>,<NA>
84,Zach abrams,1,1,2024-12-05 15:46:15,<NA>,<NA>,<NA>,<NA>,<NA>
85,Zakarias Erdos,1,1,2024-12-01 22:35:57,<NA>,<NA>,<NA>,<NA>,<NA>
86,Zebulon Erdos,1,1,2024-12-05 15:46:59,<NA>,<NA>,<NA>,<NA>,<NA>

In [111]:
# Process sheets
target_cols = ["name","email","school","grade","gender","j/n"]
for key in dfs_partiful:
    df = dfs_partiful[key]
    for col in target_cols:
        if col not in df.columns:
            df[col] = pd.NA
    df = df[target_cols]
    df.columns = ["Name", "Email", "School","Grade", "Gender", "Is_Jewish"]
    # robust to only first names
    df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
    df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
    df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
    df["First Name"] = df["First Name"].astype(str).str.lower()
    df["Last Name"] = df["Last Name"].astype(str).str.lower()

    # make school lower case
    df["School"] = df["School"].astype(str).str.lower()
    df["School"] = df["School"].astype(str).str.lower()

    # make grade into class year freshman = 2028, sophomore = 2027, junior = 2026, senior = 2025
    df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)

    # gender
    df["Gender"] = df["Gender"].astype(str).str.upper()

    # is_jewish
    df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)

    df_all_people = pd.concat([df_all_people, df])

/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/2396170422.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [112]:
for key in dfs_posh:
    display(dfs_posh[key])

,name,email,order_date,registered,approved,scanned,school,grade,gender,j/n,Name,Email,School,Grade,Gender,J/N
0,Zakarias Erdos,zakarias_erdos@college.harvard.edu,02-02-2025 9:46:07 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,Jonah Gurion,jgurion1@gmail.com,02-03-2025 9:53:32 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,AJ Sachwitz,ajsachwitz@icloud.com,02-03-2025 9:53:37 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,Grace Choi,choigrace32@gmail.com,02-03-2025 9:53:50 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,Ashley Geohas,ashleygeohas@gmail.com,02-03-2025 9:54:10 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Zoe Graham,zoergraham@gmail.com,02-05-2025 10:35:03 am,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
78,Jessica Chen,jessica_chen@college.harvard.edu,02-05-2025 11:14:37 am,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
79,Amara Ukomadu,acu7519@gmail.com,02-05-2025 2:48:34 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
80,Michelle Doan,michelledoan@college.harvard.edu,02-05-2025 5:21:21 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
81,Sebastian Taubman,srtaubman@gmail.com,02-05-2025 6:44:40 pm,1,1,0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,name,email,order_date,registered,approved,scanned,school,grade,gender,j/n,Name,Email,School,Grade,Gender,J/N
0,Zakarias Erdos,zakarias_erdos@college.harvard.edu,02-10-2025 6:26:40 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,Yehudah Tor,yehudahtor@gmail.com,02-11-2025 6:05:24 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,Isabella Raskin,raskinita@hotmail.com,02-11-2025 2:50:44 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,Carly Bolton,cbolton@college.harvard.edu,02-11-2025 8:11:55 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,Eli Hoffenberg,eli.hoffenberg01@gmail.com,02-11-2025 8:11:56 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,Ellis Garver,ellis.garver@gmail.com,02-13-2025 5:38:06 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
172,Wahid Popal,wayhid123@gmail.com,02-10-2025 8:01:36 pm,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
173,Juan Josue,bigsaleh2006@gmail.com,02-12-2025 12:33:29 am,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
174,Ciaran Brayboy,ciaran@golotushealth.com,02-12-2025 11:23:40 am,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
175,Vandit Gandotra,vanditgandotra1996@gmail.com,02-12-2025 10:01:36 pm,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,name,email,order_date,registered,approved,scanned,school,grade,gender,j/n,Name,Email,School,Grade,Gender,J/N
0,Zakarias Erdos,zakarias_erdos@college.harvard.edu,02-10-2025 9:40:58 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,Yehudah Tor,yehudahtor@gmail.com,02-11-2025 6:04:29 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,Uri Rolls,urirolls@college.harvard.edu,02-11-2025 6:04:29 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,Almog H.,almogh@mit.edu,02-11-2025 11:43:55 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,Isabella Raskin,raskinita@hotmail.com,02-11-2025 11:43:56 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
5,Eli Hoffenberg,eli.hoffenberg01@gmail.com,02-11-2025 11:44:00 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
6,Sarah Dufays,sdufays@hotmail.com,02-11-2025 11:44:01 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
7,Brooke Pulling,brookepulling@gmail.com,02-11-2025 11:44:05 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8,AJ Sachwitz,ajsachwitz@icloud.com,02-11-2025 11:44:06 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9,Eddie Gonet IV,eddiegonet4@gmail.com,02-11-2025 11:44:07 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
10,Laker Newhouse,lakernewhouse@gmail.com,02-11-2025 11:44:07 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
11,Tejas Billa,tbilla@college.harvard.edu,02-11-2025 11:44:12 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
12,Carly Bolton,cbolton@college.harvard.edu,02-11-2025 11:44:13 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
13,Chris Shen,mastercys456@gmail.com,02-11-2025 11:44:14 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
14,Daniel Zhao,danielzhao2024@gmail.com,02-11-2025 11:44:15 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
15,Atara Rubinson,arubinson@college.harvard.edu,02-11-2025 11:44:23 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
16,Julien Berman,julien.d.berman@gmail.com,02-11-2025 11:44:24 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
17,Linda He,lindahe@college.harvard.edu,02-11-2025 11:44:25 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
18,Michael Oved,michaeloved@college.harvard.edu,02-11-2025 11:44:26 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
19,Skye Lam,skyelam@college.harvard.edu,02-11-2025 11:44:26 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
20,Nebus Kitessa,nebus12@mit.edu,02-11-2025 11:44:27 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
21,Patryk Wekwejt,patrykwek@gmail.com,02-11-2025 11:44:29 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
22,Nathaniel Shin,nshin@college.harvard.edu,02-11-2025 11:44:30 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
23,Zach Abrams,zach51zach@gmail.com,02-11-2025 11:44:31 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
24,Prat Mallick,pratmallick@college.harvard.edu,02-11-2025 11:44:31 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
25,Ted Sunshine,teddysunshine@icloud.com,02-11-2025 11:44:53 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
26,Vienna Sparks,viennasparks1@gmail.com,02-11-2025 11:59:22 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
27,Oscar Boccelli,oboccelli@gmail.com,02-12-2025 2:30:49 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
28,Arielle Frommer,afrommer@college.harvard.edu,02-12-2025 2:46:26 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
29,Macy Lehrer,macylehrer@gmail.com,02-12-2025 9:15:58 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
30,Esteban Vizcaino,edviz@mit.edu,02-12-2025 9:16:05 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
31,Jeremy Williams,jwilliams@college.harvard.edu,02-12-2025 1:45:46 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
32,Alex Stone,astone5704@gmail.com,02-12-2025 1:54:04 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
33,Adam Elitzur,adam.elitzur@gmail.com,02-12-2025 2:12:04 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
34,Jay Gupta,ajaygupta0475@gmail.com,02-12-2025 2:37:23 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
35,Charlie Covit,charliecovit@gmail.com,02-12-2025 2:37:24 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
36,Jordan Wasserberger,jwasserberger@college.harvard.edu,02-12-2025 3:03:51 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
37,Jeremy Dake,jdake@mba2026.hbs.edu,02-12-2025 3:27:06 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
38,Kaitlyn Hou,adventuresofmilou@gmail.com,02-12-2025 4:09:19 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
39,Emma Cox,eecox@mit.edu,02-12-2025 5:56:14 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
40,Janka Hamori,hamorijanka12@gmail.com,02-12-2025 7:30:33 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
41,Jen Mallah,jennifermallah03@gmail.com,02-12-2025 8:21:06 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
42,Jonah Gurion,jgurion1@gmail.com,02-12-2025 8:21:05 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
43,Yael Danon,yaeldanon@college.harvard.edu,02-12-2025 9:49:46 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
44,Sam Bernbaum,samuelbernbaum@gmail.com,02-12-2025 9:49:59 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
45,Morgan Casey,morgancasey@college.harvard.edu,02-12-2025 9:50:16 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
46,Maya Madar,mayamadar1016@gmail.com,02-12-2025 11:32:06 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
47,Harley Pasternak,harley.pasternak@sfpcap.com,02-13-2025 8:24:19 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
48,Jackson Selby,jackson.selby@gmail.com,02-13-2025 8:53:43 am,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
49,Serena Sara,sxsara@mit.edu,02-13-2025 2:30:20 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
50,Hannah Chung,hdchung@mit.edu,02-13-2025 3:00:48 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
51,Zoe Graham,zoergraham@gmail.com,02-13-2025 3:12:11 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
52,Adriano Arioto,adrianoarioti@gmail.com,02-13-2025 4:45:20 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
53,Aaron Joy,aaronjoy32@gmail.com,02-13-2025 7:19:14 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
54,Alex Smits,alex-smits@outlook.com,02-12-2025 2:54:12 pm,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

,name,email,order_date,registered,approved,scanned,school,grade,gender,j/n,Name,Email,School,Grade,Gender,J/N
0,Zakarias Erdos,zakarias_erdos@college.harvard.edu,01-29-2025 1:36:14 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,Yehudah Tor,yehudahtor@gmail.com,01-29-2025 3:51:31 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,Zach Abrams,zach51zach@gmail.com,02-01-2025 4:01:47 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,Sharbel Mikhail,sharbelmikhail2006@outlook.com,02-01-2025 4:03:54 pm,1,1,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,Faruk Oztok,farukoztok2012@gmail.com,02-01-2025 4:03:57 pm,1,1,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,David Aboge,abogehh@gmail.com,02-06-2025 11:08:36 pm,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
672,Adam Morley-O’Hara,adammohara06@gmail.com,02-06-2025 11:37:41 pm,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
673,Lucy Stewart,stewluj@outlook.com,02-07-2025 12:01:47 am,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
674,Maria Bueno,alejandrabueno2006@hotmail.com,02-07-2025 12:02:31 am,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
675,Nari Shin,narishinhong@gmail.com,02-07-2025 12:08:25 am,1,0,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [113]:
# Process sheets
target_cols = ["name","email","school","grade","gender","j/n"]
for key in dfs_posh:
    df = dfs_posh[key]
    for col in target_cols:
        if col not in df.columns:
            df[col] = pd.NA
    df = df[target_cols]
    df.columns = ["Name", "Email", "School","Grade", "Gender", "Is_Jewish"]
    # robust to only first names
    df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
    df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
    df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
    df["First Name"] = df["First Name"].astype(str).str.lower()
    df["Last Name"] = df["Last Name"].astype(str).str.lower()

    # make school lower case
    df["School"] = df["School"].astype(str).str.lower()
    df["School"] = df["School"].astype(str).str.lower()

    # make grade into class year freshman = 2028, sophomore = 2027, junior = 2026, senior = 2025
    df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)

    # gender
    df["Gender"] = df["Gender"].astype(str).str.upper()

    # is_jewish
    df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)

    df_all_people = pd.concat([df_all_people, df])

/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["First Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Last Name"] = df["Last Name"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["School"] = df["School"].astype(str).str.lower()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Gender"] = df["Gender"].astype(str).str.upper()
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/3094282909.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)

In [114]:
import copy
dfs_others["Camel X BSMNT - RSVPS DUP"] = copy.deepcopy(dfs_others["Camel X BSMNT - RSVPS"]).rename(columns={"Emails": "Email"})
dfs_others["Camel X BSMNT - RSVPS"] = dfs_others["Camel X BSMNT - RSVPS"].rename(columns={"Email": "Emails", "School Email": "Email"})
for key in dfs_others.keys():
    print(key)
    display(dfs_others[key])

Camel X BSMNT - RSVPS

,Unnamed: 0,Name,Emails,Email,School,Grade,Gender,J/N
0,NaN,Zakarias Erdos,zakarias_erdos@college.harvard.edu,zakarias_erdos@college.harvard.edu,Harvard,Junior,M,J
1,NaN,Yehudah Tor,yehudahtor@gmail.com,Yehudahtor@college.harvard.edu,Harvard,Freshman,M,J
2,NaN,Zach Abrams,zach51zach@gmail.com,zachabrams@college.harvard.edu,Harvard,Junior,M,J
3,NaN,Sharbel Mikhail,sharbelmikhail2006@outlook.com,smikhail@college.harvard.edu,Harvard,Freshman,M,N
4,NaN,Faruk Oztok,farukoztok2012@gmail.com,farukoztok@college.harvard.edu,Harvard,Junior,M,N
...,...,...,...,...,...,...,...,...
702,NaN,Ari Meron,ameron505@gmail.com,ameron1@college.harvard.edu,Harvard,Freshman,M,J
703,NaN,Adam Morley-O’Hara,adammohara06@gmail.com,NaN,not harvard,NaN,NaN,NaN
704,NaN,Lucy Stewart,stewluj@outlook.com,lucystewart@college.harvard.edu,Harvard,Freshman,F,N
705,NaN,Maria Bueno,alejandrabueno2006@hotmail.com,NaN,Harvard,Freshman,F,N
706,NaN,Nari Shin,narishinhong@gmail.com,narishin@college.harvard.edu,Harvard,Freshman,F,N

Community Dinners II - Attendees

,Unnamed: 0,Name,Email,School,Grade,Gender,J/N
0,NaN,Yael Danon,yaeldanon@college.harvard.edu,Harvard,Freshman,F,J
1,NaN,AJ Sachwitz,ajsach@mit.edu,MIT,Freshman,M,J
2,NaN,Ben Shaer,Shaer.ben@gmail.com,MIT,Freshman,M,J
3,NaN,Alana Fuentes,alanafuenteslartigaut@college.harvard.edu,Harvard,Freshman,F,N
4,NaN,Isabella Raskin Calvo,isabellaraskin@college.harvard.edu,Harvard,Freshman,F,J
5,NaN,Dominic Zuniga,NaN,MIT,NaN,M,NaN
6,NaN,Liam Gibbons,NaN,MIT,NaN,M,NaN
7,NaN,Will Savage,NaN,MIT,NaN,M,NaN
8,NaN,Kate Wei,klwei@mit.edu,MIT,Freshman,F,N
9,NaN,Frances Berglund,francesberglund@college.harvard.edu,Harvard,Freshman,F,N
10,NaN,Yehudah Tor,Yehudahtor@college.harvard.edu,Harvard,Freshman,M,J
11,NaN,Logan Goodman,Logang06@mit.edu,MIT,Freshman,F,J
12,NaN,Jonah Gurion,Jgurion@mit.edu,MIT,Freshman,M,J
13,NaN,Colin Kamhi,colinkamhi@gmail.com,MIT,Freshman,M,NaN
14,NaN,Garrett Dyson,NaN,MIT,NaN,M,NaN
15,NaN,Qingqing Ouyang,NaN,MIT,NaN,NaN,NaN
16,NaN,Victoria Paesano,vpaesano@mit.edu,MIT,Sophomore,M,N
17,NaN,Jack Minor,Jbminor@mit.edu,MIT,Senior,M,J
18,NaN,María Santos,NaN,MIT,NaN,F,NaN
19,NaN,Wilson Cheung,wilsoncheung@college.harvard.edu,Harvard,Freshman,M,N
20,NaN,Robert Fogel,robertfogel@college.harvard.edu,Harvard,Senior,M,J
21,NaN,Robbie Khazan,bobert@mit.edu,MIT,Junior,M,J
22,NaN,Doron Ben Haim,doronbenhaim@college.harvard.edu,Harvard,Sophomore,M,J
23,NaN,Zach Abrams,zachabrams@college.harvard.edu,Harvard,Junior,M,J
24,NaN,Jennifer Mallah,jmallah@mit.edu,MIT,Senior,F,N
25,NaN,Aaron Becker,ambecker@mit.edu,MIT,NaN,M,NaN
26,NaN,Miguel Action,NaN,MIT,NaN,M,NaN
27,NaN,Rajan Bhargava,Rbhargava@college.harvard.edu,Harvard,Junior,M,N
28,NaN,Julia Alvarenga,juliasantosdealvarenga@college.harvard.edu,Harvard,Junior,F,N
29,NaN,Will Sherwood,wsherwood@college.harvard.edu,Harvard,Sophomore,M,J
30,NaN,Maia Posternack,maiaposternack@college.harvard.edu,Harvard,Junior,F,J
31,NaN,Zakarias Erdos,zakarias_erdos@college.harvard.edu,Harvard,Junior,M,J
32,NaN,Ari Kaufman,arikaufman@college.harvard.edu,Harvard,Sophomore,M,J
33,NaN,Jen Ben Arye,jen_ben@mit.edu,MIT,Sophomore,F,J
34,NaN,Tesia Thomas,tesiathomas@college.harvard.edu,Harvard,Junior,F,N
35,NaN,Jane Lichtman,janelichtman@college.harvard.edu,Harvard,Junior,F,J
36,NaN,Dan Erasmus,derasmus@college.harvard.edu,Harvard,Sophomore,M,N
37,NaN,Paz Meyers,pazmeyers@college.harvard.edu,Harvard,Senior,M,J
38,NaN,Kevin Zhu,kbzhu@mit.edu,MIT,Sophomore,M,N
39,NaN,Julie Steele,NaN,MIT,NaN,F,NaN
40,NaN,Spruce Campbell,NaN,MIT,NaN,M,NaN
41,NaN,Uri Rolls,urirolls@college.harvard.edu,Harvard,Sophomore,M,J
42,NaN,Janka Hamori,jankah@mit.edu,MIT,Senior,F,N
43,NaN,Ted Sunshine,theodore_sunshine@college.harvard.edu,Harvard,Junior,M,J
44,NaN,Ece Alkan,idilecealkan@college.harvard.edu,Harvard,Junior,F,N
45,NaN,Demir Alp,demiralp@college.harvard.edu,Harvard,Sophomore,M,N
46,NaN,Maya Shiloni,maya_shiloni@college.harvard.edu,Harvard,Junior,F,J
47,NaN,Delphine Protopapas,dtproto@mit.edu,MIT,Junior,F,N
48,NaN,Almog Hilel,almogh@mit.edu,MIT,Senior,M,J
49,NaN,Steven Blank,Stevenblank@college.harvard.edu,Harvard,Junior,M,J
50,NaN,Luke Williams,luke_williams@college.harvard.edu,Harvard,Freshman,M,N
51,NaN,Brendon Lau,brendonlau@college.harvard.edu,Harvard,Junior,M,N
52,NaN,Tara Razaei,NaN,MIT,NaN,F,NaN

Camel X BSMNT - RSVPS DUP

,Unnamed: 0,Name,Email,School Email,School,Grade,Gender,J/N
0,NaN,Zakarias Erdos,zakarias_erdos@college.harvard.edu,zakarias_erdos@college.harvard.edu,Harvard,Junior,M,J
1,NaN,Yehudah Tor,yehudahtor@gmail.com,Yehudahtor@college.harvard.edu,Harvard,Freshman,M,J
2,NaN,Zach Abrams,zach51zach@gmail.com,zachabrams@college.harvard.edu,Harvard,Junior,M,J
3,NaN,Sharbel Mikhail,sharbelmikhail2006@outlook.com,smikhail@college.harvard.edu,Harvard,Freshman,M,N
4,NaN,Faruk Oztok,farukoztok2012@gmail.com,farukoztok@college.harvard.edu,Harvard,Junior,M,N
...,...,...,...,...,...,...,...,...
702,NaN,Ari Meron,ameron505@gmail.com,ameron1@college.harvard.edu,Harvard,Freshman,M,J
703,NaN,Adam Morley-O’Hara,adammohara06@gmail.com,NaN,not harvard,NaN,NaN,NaN
704,NaN,Lucy Stewart,stewluj@outlook.com,lucystewart@college.harvard.edu,Harvard,Freshman,F,N
705,NaN,Maria Bueno,alejandrabueno2006@hotmail.com,NaN,Harvard,Freshman,F,N
706,NaN,Nari Shin,narishinhong@gmail.com,narishin@college.harvard.edu,Harvard,Freshman,F,N

In [115]:
# Process sheets
target_cols = ["Name","Email","School","Grade","Gender","J/N"]
for key in dfs_others:
    df = dfs_others[key]
    for col in target_cols:
        if col not in df.columns:
            df[col] = pd.NA
    df = df[target_cols]
    df.columns = ["Name", "Email", "School","Grade", "Gender", "Is_Jewish"]
    # robust to only first names
    df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
    df["Last Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[-1])
    df["Last Name"] = df.apply(lambda x: pd.NA if pd.isna(x["Last Name"]) else x["Last Name"] if x["Last Name"] != x["First Name"] else pd.NA, axis=1)
    df["First Name"] = df["First Name"].astype(str).str.lower()
    df["Last Name"] = df["Last Name"].astype(str).str.lower()

    # make school lower case
    df["School"] = df["School"].astype(str).str.lower()
    df["School"] = df["School"].astype(str).str.lower()

    # make grade into class year freshman = 2028, sophomore = 2027, junior = 2026, senior = 2025
    df["Grade"] = df["Grade"].apply(lambda x: pd.NA if pd.isna(x) else 2028 if x.lower() == "freshman" else 2027 if x.lower() == "sophomore" else 2026 if x.lower() == "junior" else 2025 if x.lower() == "senior" else pd.NA)

    # gender
    df["Gender"] = df["Gender"].astype(str).str.upper()

    # is_jewish
    df["Is_Jewish"] = df["Is_Jewish"].apply(lambda x: pd.NA if pd.isna(x) else True if x.lower() == "j" else False if x.lower() == "n" else pd.NA)

    df_all_people = pd.concat([df_all_people, df])

/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/550902276.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])
/var/folders/w_/8xv4dl8n2rv9z7xy2ms9hy700000gn/T/ipykernel_56949/550902276.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["First Name"] = df["Name"].apply(lambda x: pd.NA if pd.isna(x) else x.split(" ")[0])

In [117]:
print(f"Started with {total_len} currently at {len(df_all_people)}")

Started with 3739 currently at 4446

In [ ]:
df_all_people = df_all_people.iloc[:, 1:-1]
df_all_people.to_csv("all_people_raw.csv", index=False)

# Cleaning

In [1]:
import pandas as pd
df_all_people  = pd.read_csv("all_people_raw.csv")
# Define all strings representing missing values
na_values = ['NaN', 'nan', '<NaN>', 'NA', 'N/A', 'null', 'NULL', 'NAN']

# Replace them with pd.NA
df_all_people = df_all_people.replace(na_values, pd.NA)
df_all_people = df_all_people.replace("not harvard", pd.NA)
df_all_people

,First Name,Last Name,Email,School,Grade,Gender,Is_Jewish
0,zakarias,erdos,NaN,harvard,2026.0,M,True
1,zach,abrams,NaN,harvard,2026.0,M,True
2,jen,arye,NaN,mit,2027.0,F,True
3,logan,goodman,NaN,mit,2028.0,F,True
4,kim,nahari,NaN,harvard,2026.0,F,True
...,...,...,...,...,...,...,...
4441,ari,meron,ameron505@gmail.com,harvard,2028.0,M,True
4442,adam,morley-o’hara,adammohara06@gmail.com,<NA>,NaN,<NA>,NaN
4443,lucy,stewart,stewluj@outlook.com,harvard,2028.0,F,False
4444,maria,bueno,alejandrabueno2006@hotmail.com,harvard,2028.0,F,False
4445,nari,shin,narishinhong@gmail.com,harvard,2028.0,F,False

In [ ]:
from fuzzywuzzy import fuzz 
def compute_match_score(rowA, rowB):
    score = 0.0
    
    # auto merge if emails are the same
    if pd.notna(rowA["Email"]) and pd.notna(rowB["Email"]):
        if rowA["Email"] == rowB["Email"]:
            score += 50.0

    # 1. Fuzzy match first names
    if pd.notna(rowA["First Name"]) and pd.notna(rowB["First Name"]):
        ratio = fuzz.ratio(str(rowA["First Name"]).lower(), str(rowB["First Name"]).lower())
        # If ratio is above 90 => 1 point, above 80 => 0.5 point, else 0
        if ratio > 90:
            score += 1.0
    
    # 2. Exact match last names
    if pd.notna(rowA["Last Name"]) and pd.notna(rowB["Last Name"]):
        if rowA["Last Name"].strip().lower() == rowB["Last Name"].strip().lower():
            score += 1.0
        else:
            score -= 2.0
    
    # 3. Same school
    if pd.notna(rowA["School"]) and pd.notna(rowB["School"]):
        if rowA["School"].lower() == rowB["School"].lower():
            score += 1.0
        else:
            score -= 2.0

    # 4. Same grade
    if pd.notna(rowA["Grade"]) and pd.notna(rowB["Grade"]):
        if rowA["Grade"] == rowB["Grade"]:
            score += 1.0
        else:
            score -= 1.0
    
    # 5. Same gender
    if pd.notna(rowA["Gender"]) and pd.notna(rowB["Gender"]):
        if rowA["Gender"] == rowB["Gender"]:
            score += 0.5
        else:
            score -= 2.0

    # 6. Same is_jewish
    if pd.notna(rowA["Is_Jewish"]) and pd.notna(rowB["Is_Jewish"]):
        if rowA["Is_Jewish"] == rowB["Is_Jewish"]:
            score += 1.0
        else:
            score -= 0.5
    
    return score

def find_duplicates(df, score_threshold=1.0):
    """
    Returns a list of tuples (i, j, score) for likely duplicates.
    We'll do an O(n^2) approach here for simplicity.
    """
    potential_dupes = []
    for i in range(len(df)):
        for j in range(i+1, len(df)):
            rowA = df.iloc[i]
            rowB = df.iloc[j]
            s = compute_match_score(rowA, rowB)
            if s >= score_threshold:  # Only return if the score is at least 1
                potential_dupes.append((i, j, s))
    return potential_dupes


def merge_records(rowA, rowB):
    """
    Return a new 'merged' Series where we keep the best info from rowA and rowB.
    For emails, we create a list of unique emails.
    """
    merged = {}
    
    # Merge first name - if rowA has data, keep it; otherwise use rowB
    # Or you can pick the "longer" or "more complete" name, etc.
    merged["First Name"] = rowA["First Name"] if pd.notna(rowA["First Name"]) else rowB["First Name"]
    
    # Similarly for last name
    merged["Last Name"] = rowA["Last Name"] if pd.notna(rowA["Last Name"]) else rowB["Last Name"]
    
    # School, Grade, Gender, etc. - same pattern
    merged["School"] = rowA["School"] if pd.notna(rowA["School"]) else rowB["School"]
    merged["Grade"]  = rowA["Grade"]  if pd.notna(rowA["Grade"])  else rowB["Grade"]
    merged["Gender"] = rowA["Gender"] if pd.notna(rowA["Gender"]) else rowB["Gender"]
    
    # For is_jewish, pick one if the other is None, or if they match. 
    if pd.isna(rowA["Is_Jewish"]):
        merged["Is_Jewish"] = rowB["Is_Jewish"]
    else:
        merged["Is_Jewish"] = rowA["Is_Jewish"]
    
    # Combine emails into a list
    emails = set()
    if pd.notna(rowA["Email"]):
        emails.add(rowA["Email"])
    if pd.notna(rowB["Email"]):
        emails.add(rowB["Email"])
        
    merged["Email"] = list(emails)  # store as a list
    
    return pd.Series(merged)

In [ ]:
def process_duplicates(df, auto_merge_threshold=2.5, manual_review_threshold=2.0):
    """
    - If score >= auto_merge_threshold => auto-merge
    - Else if score >= manual_review_threshold => ask user to confirm
    - Below manual_review_threshold => ignore
    """
    dupes = find_duplicates(df, score_threshold=manual_review_threshold)
    
    # We'll store merges in a list of (i, j, merged_row)
    merges_to_perform = []
    rows_to_drop = set()
    
    for (i, j, score) in dupes:
        if i in rows_to_drop or j in rows_to_drop:
            # Already merged or dropped, skip
            continue
        
        if score >= auto_merge_threshold:
            # Auto-merge
            merged_row = merge_records(df.loc[i], df.loc[j])
            merges_to_perform.append((i, j, merged_row))
        else:
            # Prompt user
            print(f"\nPossible duplicate (score={score:.2f}):")
            print("Row i:\n", df.loc[i])
            print("Row j:\n", df.loc[j])
            choice = input("Merge these? [y/n] ")
            if choice.lower().startswith("y"):
                merged_row = merge_records(df.loc[i], df.loc[j])
                merges_to_perform.append((i, j, merged_row))

    # Now actually perform merges
    # For each pair, we create a new row in the DF (or update one of them),
    # then mark the other as dropped
    for (i, j, merged_row) in merges_to_perform:
        # Put the merged row in the place of i, and drop j
        df.loc[i] = merged_row
        rows_to_drop.add(j)
    
    # Drop the merged rows
    df.drop(rows_to_drop, inplace=True)
    
    # Re-index if you like
    df.reset_index(drop=True, inplace=True)
    
    return df

# Example usage
df_merged = process_duplicates(df_all_people)

In [1]:
import pandas as pd

df = pd.read_csv("final/events.csv")
df

,id,event_name,category,location,start_datetime,description
0,0,prelaunch,speaker,sunshine residence,2024-09-26 17:30:00-05:00,Get together of students at the sunshine resid...
1,1,launch,party,prudential center,2024-09-26 19:30:00-05:00,Party at the top of the prudential center
2,2,russell house,speaker dinner,russell house,2024-10-14 19:30:00-05:00,Join us for our first official event this comi...
3,3,viale,speaker dinner,viale,2024-10-30 19:45:00-05:00,We’re excited to invite you to the next event ...
4,4,sababa nights,party,Dx,2024-11-07 22:00:00-05:00,Disco Rave this Thursday! Harvard x MIT party ...
5,5,amplify,speaker dinner,bar enza,2024-11-13 19:00:00-05:00,Amplify VC hosted/funded dinner at bar enza
6,6,community dinners I,community dinner,various,2024-11-20 19:00:00-05:00,"Community dinners hosted by Camel, monday, wed..."
7,7,secret sip,community dinner,sunshine residence,2024-12-06 18:00:00-05:00,Join us for a Shabbat dinner and afterparty wi...
8,8,pentera,speaker dinner,daedalus,2025-02-05 19:00:00-05:00,"Hi Everyone! This coming Wednesday, Amitai Rat..."
9,9,bsmnt,party,bsmnt,2025-02-06 21:00:00-05:00,There’s a Camel in the BSMNT. We don’t know ho...
10,10,zelnick speaker,speaker,sheraton commander,2025-02-13 18:00:00-05:00,"This Thursday (February 13th) at 6 pm, we are ..."
11,11,zelnick dinner,speaker dinner,gufo,2025-02-13 19:30:00-05:00,"Hi, We’re hosting a private, invite-only dinne..."
12,12,community dinners II,community dinner,various,2025-02-26 19:30:00-05:00,Community dinners hosted by Camel
13,13,camel x biotech,speaker dinner,sulmona,2025-03-12 19:30:00-05:00,Join us for an exclusive evening of conversati...